---
resources:
  - service.yaml
  - deployment.yaml
  - certificate.yaml
  - ingress.yaml


namespace: development

commonLabels:
  env: development
  app: configuration

secretGenerator:
  - name: configuration-secrets
    env: configuration-secrets.env
