name: Deploy Desktop

env:
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  CONFIGURATION_SERVER_USERNAME: ${{ secrets.CONFIGURATION_SERVER_USERNAME }}
  CONFIGURATION_SERVER_PASSWORD: ${{ secrets.CONFIGURATION_SERVER_PASSWORD }}
  GCLOUD_ZONE_DEVELOPMENT: ${{ secrets.GCLOUD_ZONE_DEVELOPMENT }}
  GCLOUD_ZONE_PRODUCTION: ${{ secrets.GCLOUD_ZONE_DEVELOPMENT }}
  GCLOUD_PROJECT_DEVELOPMENT: ${{ secrets.GCLOUD_PROJECT_DEVELOPMENT }}
  GCLOUD_PROJECT_PRODUCTION: ${{ secrets.GCLOUD_PROJECT_DEVELOPMENT }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  CONFIGURATION_SERVER_URI_PRODUCTION: https://configuration.bootifulpodcast.fm
  CONFIGURATION_SERVER_URI_DEVELOPMENT: https://configuration.development.bootifulpodcast.fm
  GKE_CLUSTER_NAME_PRODUCTION: bootiful-podcast-production
  GKE_CLUSTER_NAME_DEVELOPMENT: bootiful-podcast-development


on:
  repository_dispatch:
    types: [ deploy-production-event, deploy-development-event ]
  create:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: bootiful-podcast/bp-mode-github-action@v34

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ env.GCLOUD_PROJECT }}
          export_default_credentials: true

      - run: |
          gcloud config set project $GCLOUD_PROJECT
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone "$GCLOUD_ZONE" --project ${GCLOUD_PROJECT}

#      - uses: joshlong/config-client-github-action@v29
#        with:
#          config-server-uri: http://${CONFIGURATION_SERVER_HOST}
#          config-server-username: ${{ secrets.CONFIGURATION_SERVER_USERNAME  }}
#          config-server-password: ${{ secrets.CONFIGURATION_SERVER_PASSWORD  }}
#          config-server-application-id: deployment
#          config-server-profile: ${{ env.BP_MODE_LOWERCASE }}

      - uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Deploy Desktop
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$GITHUB_WORKSPACE/bin/:$PATH
          (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.14.2/pack-v0.14.2-linux.tgz" | sudo tar -C $GITHUB_WORKSPACE/bin/ --no-same-owner -xzv pack)
          ./deploy/deploy.sh
